combinations:
  v21p6sim_rotd50:
    ims:
      - "PGV"
      - "PGA"
      - "pSA_0.1"
      - "pSA_0.2"
      - "pSA_0.5"
      - "pSA_1.0"
      - "pSA_2.0"
      - "pSA_3.0"
      - "pSA_5.0"
    excd_prob:
      - {percentage: 50, years: 50}
      - {percentage: 10, years: 50}
      - {percentage: 2, years: 50}
    n_procs: 3
