# docker-compose.yml
version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=localdev
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=test
      # TZ is not necessary.
      - TZ=Pacific/Auckland
    # Assuming we don't mind store db_data directory in the current directory.
    # For instance, the directory could look like this (Database is a root directory)
    # Database
    # |- .env
    # |- docker-compose.yml
    # |- db_data <- this directory will be created upon using the following volumes command
    # Now we store data in this directory (externally), not inside the docker container.
    volumes:
      - ./db_data:/var/lib/mysql
  # Not necessary for AWS but your local setup due to having DB Viewer via a web browser
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data:
